name: Convert perf.data to AFDO

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm clang unzip

    - name: Download or Prepare perf_to_profile
      run: |
        # 示例使用 ChromeOS 的预构建工具（或你可以上传二进制）
        mkdir -p tools
        curl -L -o tools/perf_to_profile \
          https://chrome-infra-packages.appspot.com/dl/infra/3pp/tools/perf_to_profile/linux-amd64/+/latest
        chmod +x tools/perf_to_profile

    - name: Convert perf.data to kernel.afdo
      run: |
        mkdir -p afdo
        tools/perf_to_profile \
          --binary=vmlinux \
          --out=afdo/kernel.afdo \
          perf.data

    - name: Upload AFDO profile
      uses: actions/upload-artifact@v4
      with:
        name: kernel-afdo
        path: afdo/kernel.afdo
