name: Build All(主工作流)

on:
  workflow_dispatch:

jobs:
  ace5pro_kpm:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      KERNEL_NAME: '-android15-8-g013ec21bba94-abogki383916444' 
      local_version: '-4k'
