name: Build All(主工作流)

on:
  workflow_dispatch:
    inputs:
      optimizer_level:
        required: true
        type: string
      options:
        required: true
        description: '目标机型'
        type: choice
        options:
          - 'oneplus_ace5_pro'
          - 'oneplus_13'
          - 'oneplus_13t'
        default: 'oneplus_ace5_pro'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      optimizer_level: ${{ inputs.optimizer_level }}
      FEIL: ${{ inputs.options }}
