name: Build All(主工作流)

on:
  workflow_dispatch:
    inputs:
      optimizer_level:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      optimizer_level: ${{ inputs.optimizer_level }}
