name: Build All(主工作流)

on:
  workflow_dispatch:

jobs:  
  generate-timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-time.outputs.timestamp }}
    steps:
      - name: Generate precise timestamp (Shanghai Time)
        id: set-time
        run: |
          TIMESTAMP=$(TZ='Asia/Shanghai' date +"%Y%m%d-%H%M%S")
          echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
          echo "Generated Shanghai timestamp: ${TIMESTAMP}"
          
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
      
 # ============== 新增聚合 Release 的作业 ============== #
  create-unified-release:
    needs: [generate-timestamp, build]
    runs-on: ubuntu-latest
    if: ${{ needs.generate-timestamp.outputs.timestamp != '' }}
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts
          pattern: AnyKernel3_*
          merge-multiple: true

      - name: Create unified release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.generate-timestamp.outputs.timestamp }}
          name: "统一内核构建 (${{ needs.generate-timestamp.outputs.timestamp }} 北京时间)"
          body: |
            ### 所有设备的内核构建
            **构建时间:** ${{ needs.generate-timestamp.outputs.timestamp }} (UTC+8)
            **包含设备:**
            - oneplus_ace5_pro
            - oneplus_13
            - oneplus_13t
            
            **优化级别:**
            - O0, O1, O2, Os, O3, Ofast
            
            **使用说明:**
            1. 下载对应设备的刷机包
            2. 在恢复模式中刷入
            3. 重启设备
          draft: false
          prerelease: false
          files: |
            all-artifacts/*.zip
            all-artifacts/*.img
            all-artifacts/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
